# Feature Scaling

    Feature Scaling is a data preprocessing technique. By preprocessing, we mean the transformations that are applied to the data before it is fed into some algorithm for some processing.
    
   
   
   
   
    <1.What is Feature Scaling?>

    Feature Scaling is a technique where we standardize the range of all independent features of a data-set. It is also called Normalization. 
    
    Generally, when we get raw data, all the features values varies on different scales. It is important to bring all the feature values on the scale so that value of one feature should not dominate over the others and hinder the performance of the learning algorithm. This process of bringing all the features values on the same scale is called feature scaling. Ensuring standardised feature values implicitly weights all features equally in their representation.
    
     Feature scaling or re-scaling of the features is performed such that they have the properties of normal distribution (most of the time) where values have standard deviation = 1, and mean = 0.
    
    
    
    
    
    <2.Why Feature Scaling is required?>
    
     Most of the real world applied machine learning algorithms are classification algorithms. Many of the classification algorithms works by calculating the distance between data points in space. If one feature has a wide range of values, then this feature is likely to dominate the distance measure between the data points over other features. Above this, if this feature proves to be insignificant in the end then, it will be hindering the algorithm results to a large extent. This will result in decrease in accuracy of the algorithm.
        
    
    
    
    
    
    <3.How Feature Scaling is applied in sklearn?>
    
     There are many ways by which we can apply feature scaling on the dataset:
        
     1. The easiest way of scaling is to use - preprocessing.scale() function 
        A numpy array of values is given as input and output is numpy array with scaled values.This will 
        scale the values in such a way that mean of the values will be 0 and standard deviation will be 1.

     2. Another method is to scale the features between given minimum and maximum values,generally between0and 1. 
        Function -preprocessing.MinMaxScaler(feature_range=(0, 1), copy=True)
        Feature_range is given in the form of tuple - (min , max)
        Copy - True (default), set it to False if you want inplace transformation

In [5]:
import numpy as np
from sklearn import preprocessing

In [4]:
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])

In [14]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
X_scaled.mean(axis = 0)

array([ 0.,  0.,  0.])

In [12]:
X_scaled.std(axis= 0)

array([ 1.,  1.,  1.])

In [15]:
scaler = preprocessing.StandardScaler() # Transfer the parameter to X
scaler.fit(X)
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [17]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])